### ISSUE TITLE
Implement React Router

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#1]
**Issue**
Currently there is no routing system in place

**Task** 
Use `react-router-dom` to implement different paths in `App.tsx`

**To-do**
- [x] Checkout a new branch 
- [x] Create a homepage component, `Home` in `components` and migrate everything currently in `App.tsx` to `Home.tsx`.
- [x] Use online documentation to create a framework for routing in react in `App.tsx`
- [x] Create one path `"/"` whose element is `Home`
- [x] Create one path `"/reservation"` whose element is `Reservation` (use same code for now)
- [x] Create one path `"/room"` whose element is `Room` (use same code for now)
- [x] Create one path `"/admin"` whose element is `Admin` (use same code for now)
- [x] Create a pull request when done
