### ISSUE TITLE
Create a Home Page

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#11]
**Issue**
All the components are pretty scattered right now. We want to organize the components based off the designs.

**Task**
Create a homepage.

**To-do**
- [ ] Add `Search` component
- [ ] Use a useState hook and if `search` is true, display `RoomGrid` component
- [ ] If `search` is false, display `Landing` component
