### ISSUE TITLE
Create a Room Grid

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#13]
**Issue**
Right now there's no organization for all the room cards that we want to have

**Task**
Use reacts grid feature to add the room cards in a grid-like fashion

**To-do**
- [x] New component `RoomGrid`
- [x] import grid from material UI
- [x] Read up on documentation [here](https://mui.com/material-ui/react-grid/)
- [x] Clara's designs indicate a grid of 3 room cards at a time
- [x] Test by calling multiple room card components
- [x] There's a lot of inspiration from club-view which you can see [here](https://github.com/cornell-dti/club-view/blob/main/frontend/src/components/ClubBoard/ClubBoard.tsx) (lot of filler code but try to find the important parts); **They use a modal, which is different, but focus on how they add the club cards**

General idea is to look like this
<img width="530" alt="image" src="https://user-images.githubusercontent.com/33362417/175794145-ffb3853d-b517-40ec-87e8-714f3f3e161b.png">
