### ISSUE TITLE
Create a Room page

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#15]
**Issue**
There is no room page right now.

**Task**
Frame a room page in order to make it easier later.

**To-do**
- [x] Create a new branch
- [x] Follow [Clara's Mid Fi](https://www.figma.com/file/po5PLGL83Hk75nqyMvvsuR/Reservations-Required?node-id=31%3A2) design to make all the room page information
- [x] Do not include the `Your Reservation` window yet. `NavBar` not necessary.
- [x] Pass in the following props and display them
+ Building Name
+ Room Number
+ Img source
+ Location
+ Capacity
+ Amenities
- [x] Make a pull request

**Comment by bonytoni** [comment]
Need to method to display image on the room page. App.tsx was modified with a Room object to hardcode the Room page.

**Comment by DylanTom** [comment]
Resolved for now. Issue will be reopened at a later date.
