### ISSUE TITLE
Set Up Authentication

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#19]
**Issue**

**Task**

**To-do**
- [ ] A

**Comment by bonytoni** [comment]
Error when user logins for first time.

**Comment by DylanTom** [comment]
@bonytoni Currently., authentication flows smoothly but we would like to fix this error. 

- [ ] Try to find the root of this error
- [ ] Correct it or explain what you tried and failed
- [ ] If you determine it's a fail, comment it here and what are other options we can try to resolve the issue

**Comment by benjamin0t** [comment]
Wait did my old code not work.

**Comment by DylanTom** [comment]
It did work, fixing the error you mentioned because its inconvenient for users to log on and have an error thrown at them because it could not fetch the username. @benjamin0t

**Comment by DylanTom** [comment]
fetch username does not load instantly, maybe run in background before rendering?
