### ISSUE TITLE
Implement Functions for Buildings

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#21]
**Issue**
There is no backend functionality right now. We want to begin this process to connect frontend and backend.

**Task**
Implement the following functions in `buildings.ts` for the backend. Add appropriate specifications, few words will do. Follow the existing routes in the file. There will most likely be a lot of clarifying questions.

**To-do**
- [x] Make sure that you have the `serviceAccount.json` file setup from the Notion page - add it to the server directory
- [x] DELETE - removes a building by its ID 
+ the path is `/:b_id`, where `b_id` can be referenced by `req.params.b_id`
- [x] POST - adds a new building with the next available ID
+ create a variable to keep track of building IDs (this will be complicated if you try to delete building number 3 and want to add building number 5, for example, will work through this)
+ the path is `/` - there is a similar function in `users.ts` which implements a POST method
- [x] POST - adds a new room with the next available ID
+ create a variable that keep track of existing room IDs
+ the path is `/:b_id/rooms/` 
+ it should add a new room with the next available ID, associated with that `:b_id` but added to the `rooms` database
- [x] GET - returns information about a room
+ returns information about a specific room by its ID
+ the path is `/:b_id/rooms/:r_id` where there are two request parameters `b_id` and `r_id`
- [x] DELETE - removes a room by its ID
+ the path is `/:b_id/rooms/:r_id`

**The last two should be the most difficult**

The idea with firebase functions is to 
+ access the collection
+ identify the appropriate document
+ wait for the data
+ send it to the frontend
