### ISSUE TITLE
Style NavBar

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#25]
**Issue**
Directly follows #7 . Need to follow high fi designs. 

**Task**
Make the navbar look pretty

**To-do**
- [x] Use existing code and add the person SVG from the figma design kit (there might be an error importing the SVG, look at `Summary.tsx` if stuck)
- [x] Create a simple dropdown menu which includes a redirect to `Profile` labeled "My reservations" and a button labeled "Sign out" (import the logout function from `firebase.ts`)
- [x] Up to your discretion, do you think we can change the baymax picture yet (also add the svg for the logo into the assets folder for now but don't add it to the code)

![image](https://user-images.githubusercontent.com/33362417/177017160-271ab01a-cc13-4d1b-8794-56d13e660e4f.png)
