### ISSUE TITLE
Create a Your Reservation Window

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#35]
**Issue**
There is no way to reserve a room currently. 

**Task**
Create a your reservation window. 

**To-do**
- [x] New component `Reserve`; Add this component to `Room`
- [x] Display current reservation data: date and time, pass in three things into props
+ date: string
+ time_start: string
+ time_end: string
(string for now, will fix later)
- [x] Add a purpose textbox - with the appropriate text in the center
- [x] Add a button to `Reserve` if signed in (make a dummy variable for now), else `Sign In to Reserve`

Try the question mark operator:

`(condition - signed in) ? button has text 1 : button has text 2`

General Idea is to look like this
![image](https://user-images.githubusercontent.com/33362417/173260854-887c1f51-2a31-488d-90bd-d084378d6a53.png)

**Comment by DylanTom** [comment]
**NEW**

The general template is created under `Summary` component, please style it according to high-fi

![image](https://user-images.githubusercontent.com/33362417/177017241-e2b9783f-3da4-469e-a093-2b01ea527268.png)
