### ISSUE TITLE
Style Sign In Pop Up

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#37]
**Issue**
We want to make the login page look pretty.

**Task**
Style the sign in page, designs will not vary much.

**To-do**
- [x] You will be working in the existing `Login` component
- [ ] Do what you can to make it look like the design shown below
- [x] The tricky part is that you have to do this development in incognito because this page will not display if you are signed in
- [x] Try to find the SVG of the google logo [here](https://commons.wikimedia.org/wiki/Category:Google_SVG_logos)
- [x] Add the svg to a new folder called `assets` in the client src directory

General idea is to look like this:
![image](https://user-images.githubusercontent.com/33362417/173263019-84382cde-1dde-44af-96e7-f542cf08cc85.png)
