### ISSUE TITLE
Create support for routes

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#4]
**Issue** 
We want to maintain the filesize and scope of `index.js`

**Task**
Implement `routes.js` which will store all the POST, GET, PUT, DELETE routes

**To-do**
- [x] Create `routes.js` in `src`
- [x] Use online documentation to see how to use express and router
- [x] Move the currently commented code in `index.js` regarding various route API calls to `routes.js`
- [x] Clean up the backend and ensure the code works by clicking the button; verify it outputs the correct message

**Comment by DylanTom** [comment]
PR Done
