### ISSUE TITLE
Initialize a lot of Components

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#5]
**Issue**
Right now the website is pretty barebones. There is no functionality or objects on the page.

**Task** 
Begin implementing some of the necessary frameworks (which may or may not eventually be used)

**To-do**
- [ ] Create a `Footer` component which stores "contact info" and a link to "Admin"
- [ ] Create a `Search` component and have it return the text `search`
- [ ] Create a `Room` component and have it return the test `room`
- [ ] Attempt to use different material UI components as possible (when you can use html button, try `@mui/material/button` or `@mui/material/typography` for fonts and text
- [ ] Once #1 is completed, add these components to `App.js`

NOTE: the design choices is currently up to you. We are just developing the initial framework to be used (or not) in the future. Do not try to style it or make it look pretty. 99% chance it will be overwritten.
