### ISSUE TITLE
User Verification

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#55]
**Issue**
Currently, there is no restrictive measures in place.

**Task**
Given four user statuses, allow permissions for specific components, features, and pages.

**To-Do**
- [x] Fetch the user status: `student`, `staff`, `admin`, `restricted`
- [x] Only allow users with status `staff` and `admin` to view the `Admin` component
- [x] Admin should have full view of the website
- [x] Student should not be able to view the `Admin` component
- [x] Restricted users will receive an error message upon sign in and must contact an admin to reassign their status - reserved for users abusing or exploiting the system
