### ISSUE TITLE
Create the ability to add a favorite

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#60]
**Issue** 
This is simple in theory but might be challenging in execution. 

**Task**
Add the ability to favorite a room card.

**To-do**
Add favorites button to room card component
- [x] Import the two SVGs from the figma high fi design. One should be `favorite_unfilled` and the other should be `favorite_filled`
- [x] Add this to the room card, no need to worry about styling
- [x] Create a useState hook - if favorite is true set it to filled and if false set it to unfilled

CHECKPOINT: The favorite icon should change by changing the value of useState

Make favorites button clickable
- [x] On click, change the icon (no need for processing yet, just make sure it can switch state)

CHECKPOINT: The favorite icon should switch by clicking it

Ensure the user is signed in

CHECKPOINT: If the user is signed in, it should switch icon. If not, there should be nothing happening because you can't favorite if you are not logged in

Let Dylan know when you are up to this, we have to make sure the backend is set up for this

+ Add this room card to user's favorites if the icon is checked
+ Remove this room card to user's favorites if the icon is unchecked
