### ISSUE TITLE
Create a NavBar

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#7]
**Issue**
Currently, there is no navbar to navigate between different components

**Task**
Create a NavBar

**To-do**
- [x] Create a branch for this new festure
- [x] Create a `NavBar` component in `components`; export it and use it in `App.tsx`
- [x] Add temporary links to "Home" and "Log In"
- [x] Add an image "logo" (pick what you want for now (can be a funny one) and add the image to a new `assets` folder and display it)
- [x] Add temporary label "Morrison Reservations"
- [x] For the sign in button, make a boolean (think about using useState) and if the variable is true (that means you are signed in), link for "Profile" and if false, link for "Sign In"
** For useState - the TLDR is that it is a pseudo-getter/setter **

`const [variable, setVariable] = useState(initialValue)` 

Also, try the question mark operator

`(condition - value of useState?) ? display one component : display the other component`

- [x] Do a rough design based off of [Clara's Mid Fi](https://www.figma.com/file/po5PLGL83Hk75nqyMvvsuR/Reservations-Required?node-id=31%3A2) (do not go overboard as it will most likely be reworked), **most important is making the current page label bolded in the navbar**
- [x] Make a pull request when done

General idea is to look like this
![image](https://user-images.githubusercontent.com/33362417/173260986-99111626-3de8-4563-8765-137546eb1bff.png)
