### ISSUE TITLE
Create a Burger Menu

### ISSUE THREAD

**Issue by DylanTom** [Reservations-Required/reserve-web#9]
**Issue** 
Want a way to hide some of the clutter on the screen

**Task**
Implement a burger menu

**To-Do**
- [ ] Create a `Burger` component in `components`; be able to export it and use it in `NavBar`
- [ ] Add temporary text for now
- [ ] In `NavBar`, implement a `useState()` hook for opening/closing functionality
- [ ] Pass props into the Burger component (reach out if you need help, this is very vague directions)
